### ISSUE TITLE
[Feature Request] Nord Theme 

### ISSUE THREAD

**Issue by bungadrum** [vinceliuice/Orchis-theme#324] opened 2023-04-17 16:10 UTC
Could you  add  a Nordic theme as well similar to what Graphite has ?

Hex color samples:
#2b303c
#313744

**Comment by astro-ray** [comment] 2023-07-10 14:20
duplicate of #59 
and since b47fbe1872e26cb987e71bc9b398b66dde4ee18c it supports Nord variant

**Closed** 2023-07-10 16:56 UTC
